language: node_js
sudo: required
dist: trusty
node_js:
  - "stable"
before_script:
  - npm install -g firebase-tools
  - npm install
  - npm run lint

script:
  - ng build --env=prod

cache:
  directories:
    - "node_modules"

deploy:
  provider: firebase
  token:  "$FIREBASE_TOKEN"
  project: "show-tarto"

notifications:
  slack: amazingshowtarto:8qbtbh3aiSPOHeNmd0Eimav0
