language: node_js
node_js:
  - "stable"

before_install:
  - npm install -g firebase-tools

install:
  - npm install

before_script:
  - npm run lint

script:
  - ng build --env=prod

deploy:
    provider: firebase
    token:  "$FIREBASE_TOKEN"
    project: "show-tarto"

 notifications:
    slack: amazingshowtarto:8qbtbh3aiSPOHeNmd0Eimav0
