language: node_js
node_js:
  - "stable"
install:
  - npm install -g firebase-tools

before_script:
  - npm install
script:
  - npm run lint
  - ng build -prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
notifications:
    slack: epmbetsupergroup:zHdM0sziVroLLnUdzqS5hoQu